<?php

using('App.Code.Data.ActiveRecord.NActiveRecord');
using('System.Data.ActiveRecord.TActiveRecordCriteria');

/**
 * Auto generated by PRADO - WSAT on 2016-08-22 12:59:12.
 * @author
 */
class ClotheRecord extends NActiveRecord
{
    const TABLE = 'clothes';

    public $clothe_id;
    public $username;
    public $title;
    public $size;
    public $color;
    public $tags;

    public static function finder($className = __CLASS__)
    {
        return parent::finder($className);
    }

    public static $RELATIONS = array();

    public function __toString()
    {
        return '';
    }

    /**
     * @return bool
     */
    protected function canHandleOnUpdate()
    {
        return true;
    }
}